version: "3.9"
services:

  ## Prefect Agent
  agent:
    image: prefecthq/prefect:2.10.17-python3.9
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "docker-work"]
    environment:
      - PREFECT_API_URL=http://${HOST_URL}:4200/api

volumes:
  prefect:
  db:
  minio:
networks:
  default:
    name: prefect-worker
